2024-05-27_13-33-04: DF Exception: Sub: R1004D, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-33-04: DF Exception: Sub: R1016M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-33-08: DF Exception: Sub: R1013E, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-33-11: DF Exception: Sub: R1021D, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-33-11: DF Exception: Sub: R1016M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-33-18: DF Exception: Sub: R1026D, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-33-54: DF Exception: Sub: R1035M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-34-00: DF Exception: Sub: R1036M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-34-03: DF Exception: Sub: R1041M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-34-05: DF Exception: Sub: R1042M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-34-12: DF Exception: Sub: R1050M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-34-30: DF Exception: Sub: R1045E, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-34-31: DF Exception: Sub: R1060M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-34-38: DF Exception: Sub: R1061T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-34-42: DF Exception: Sub: R1065J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-34-44: DF Exception: Sub: R1045E, Sess: 1, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-34-49: DF Exception: Sub: R1065J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-34-50: DF Exception: Sub: R1065J, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-34-52: DF Exception: Sub: R1066P, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-34-54: DF Exception: Sub: R1065J, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-34-55: DF Exception: Sub: R1066P, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-34-55: DF Exception: Sub: R1066P, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-35-05: DF Exception: Sub: R1074M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-35-05: DF Exception: Sub: R1069M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-35-11: DF Exception: Sub: R1075J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-35-15: DF Exception: Sub: R1083J, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-35-16: DF Exception: Sub: R1086M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-35-24: DF Exception: Sub: R1092J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-35-31: DF Exception: Sub: R1093J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-35-54: DF Exception: Sub: R1107J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-35-56: DF Exception: Sub: R1107J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-36-30: DF Exception: Sub: R1111M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-36-35: DF Exception: Sub: R1111M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-36-45: DF Exception: Sub: R1119P, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-36-49: DF Exception: Sub: R1130M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-36-49: DF Exception: Sub: R1127P, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-36-59: DF Exception: Sub: R1135E, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-36-59: DF Exception: Sub: R1135E, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-37-05: DF Exception: Sub: R1138T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-37-06: DF Exception: Sub: R1138T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-37-12: DF Exception: Sub: R1141T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-37-13: DF Exception: Sub: R1141T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-37-14: DF Exception: Sub: R1141T, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-37-37: DF Exception: Sub: R1147P, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-38-13: DF Exception: Sub: R1163T, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-38-15: DF Exception: Sub: R1169P, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-38-15: DF Exception: Sub: R1167M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-38-18: DF Exception: Sub: R1170J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-38-20: DF Exception: Sub: R1170J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-38-25: DF Exception: Sub: R1178P, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-38-35: DF Exception: Sub: R1171M, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-38-51: DF Exception: Sub: R1181E, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-38-53: DF Exception: Sub: R1181E, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-38-57: DF Exception: Sub: R1181E, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-38-57: DF Exception: Sub: R1184M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-39-03: DF Exception: Sub: R1187P, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-39-03: DF Exception: Sub: R1188C, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-39-04: DF Exception: Sub: R1189M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-39-05: DF Exception: Sub: R1186P, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-39-09: DF Exception: Sub: R1191J, Sess: 1, ValueError, Events must correspond to the session with which the reader was initialized: 1 (events correspond to 0), file: create_events_mne.py, line no: 452
2024-05-27_13-39-18: DF Exception: Sub: R1192C, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-39-20: DF Exception: Sub: R1192C, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-39-25: DF Exception: Sub: R1192C, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-39-28: DF Exception: Sub: R1201P, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-39-28: DF Exception: Sub: R1202M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-39-28: DF Exception: Sub: R1202M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-39-33: DF Exception: Sub: R1204T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-40-08: DF Exception: Sub: R1217T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-40-21: DF Exception: Sub: R1222M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-40-30: DF Exception: Sub: R1226D, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-40-33: DF Exception: Sub: R1226D, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-40-35: DF Exception: Sub: R1226D, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-40-37: DF Exception: Sub: R1226D, Sess: 4, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-40-39: DF Exception: Sub: R1227T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-40-43: DF Exception: Sub: R1229M, Sess: 0, ValueError, Events must correspond to the session with which the reader was initialized: 0 (events correspond to 1), file: create_events_mne.py, line no: 452
2024-05-27_13-40-50: DF Exception: Sub: R1230J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-40-52: DF Exception: Sub: R1235E, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-40-52: DF Exception: Sub: R1231M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-40-57: DF Exception: Sub: R1235E, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-41-31: DF Exception: Sub: R1243T, Sess: 1, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-41-42: DF Exception: Sub: R1245E, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-41-50: DF Exception: Sub: R1247P, Sess: 1, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-41-59: DF Exception: Sub: R1247P, Sess: 2, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-42-02: DF Exception: Sub: R1247P, Sess: 3, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-42-10: DF Exception: Sub: R1251M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-42-15: DF Exception: Sub: R1247P, Sess: 5, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-42-34: DF Exception: Sub: R1261P, Sess: 1, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-42-36: DF Exception: Sub: R1264P, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-42-39: DF Exception: Sub: R1264P, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-42-52: DF Exception: Sub: R1266J, Sess: 3, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-43-05: DF Exception: Sub: R1269E, Sess: 3, ValueError, Events must correspond to the session with which the reader was initialized: 3 (events correspond to 10), file: create_events_mne.py, line no: 452
2024-05-27_13-43-10: DF Exception: Sub: R1271P, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-43-16: DF Exception: Sub: R1271P, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-43-22: DF Exception: Sub: R1271P, Sess: 4, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-43-24: DF Exception: Sub: R1273D, Sess: 0, ValueError, Events must correspond to the session with which the reader was initialized: 0 (events correspond to 1), file: create_events_mne.py, line no: 452
2024-05-27_13-43-26: DF Exception: Sub: R1273D, Sess: 1, ValueError, Events must correspond to the session with which the reader was initialized: 1 (events correspond to 2), file: create_events_mne.py, line no: 452
2024-05-27_13-43-27: DF Exception: Sub: R1273D, Sess: 2, ValueError, Events must correspond to the session with which the reader was initialized: 2 (events correspond to 3), file: create_events_mne.py, line no: 452
2024-05-27_13-43-31: DF Exception: Sub: R1274T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-43-32: DF Exception: Sub: R1274T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-43-36: DF Exception: Sub: R1274T, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-43-39: DF Exception: Sub: R1275D, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-43-44: DF Exception: Sub: R1277J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-43-45: DF Exception: Sub: R1277J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-43-57: DF Exception: Sub: R1278E, Sess: 10, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-44-12: DF Exception: Sub: R1286J, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-44-23: DF Exception: Sub: R1290M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-44-24: DF Exception: Sub: R1291M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-44-28: DF Exception: Sub: R1291M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-44-29: DF Exception: Sub: R1302M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-44-29: DF Exception: Sub: R1302M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-44-31: DF Exception: Sub: R1293P, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-44-38: DF Exception: Sub: R1313J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-44-43: DF Exception: Sub: R1303E, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-44-48: DF Exception: Sub: R1317D, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-44-58: DF Exception: Sub: R1320D, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-45-03: DF Exception: Sub: R1320D, Sess: 1, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-45-05: DF Exception: Sub: R1320D, Sess: 2, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-45-09: DF Exception: Sub: R1321M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-45-09: DF Exception: Sub: R1321M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-45-13: DF Exception: Sub: R1324M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-46-10: DF Exception: Sub: R1334T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-46-38: DF Exception: Sub: R1338T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-47-32: DF Exception: Sub: R1351M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-47-32: DF Exception: Sub: R1351M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-47-37: DF Exception: Sub: R1354E, Sess: 2, ValueError, could not broadcast input array from shape (124,100) into shape (124), file: create_events_mne.py, line no: 452
2024-05-27_13-47-52: DF Exception: Sub: R1361C, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-48-15: DF Exception: Sub: R1361C, Sess: 1, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-48-23: DF Exception: Sub: R1364C, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-48-35: DF Exception: Sub: R1364C, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-48-40: DF Exception: Sub: R1366J, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-48-41: DF Exception: Sub: R1368T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-48-51: DF Exception: Sub: R1372C, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-48-51: DF Exception: Sub: R1372C, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-49-03: DF Exception: Sub: R1372C, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-49-15: DF Exception: Sub: R1375C, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-49-17: DF Exception: Sub: R1375C, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-49-22: DF Exception: Sub: R1375C, Sess: 4, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-49-22: DF Exception: Sub: R1375C, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-49-37: DF Exception: Sub: R1378T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-49-47: DF Exception: Sub: R1378T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-50-36: DF Exception: Sub: R1383J, Sess: 1, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-50-54: DF Exception: Sub: R1384J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-50-57: DF Exception: Sub: R1384J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-51-07: DF Exception: Sub: R1386T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-51-26: DF Exception: Sub: R1388T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-51-30: DF Exception: Sub: R1388T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-51-32: DF Exception: Sub: R1389J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-51-35: DF Exception: Sub: R1389J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-51-37: DF Exception: Sub: R1389J, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-51-39: DF Exception: Sub: R1389J, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-51-41: DF Exception: Sub: R1390M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-51-42: DF Exception: Sub: R1390M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-51-44: DF Exception: Sub: R1390M, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-51-46: DF Exception: Sub: R1390M, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-51-54: DF Exception: Sub: R1393T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-51-56: DF Exception: Sub: R1393T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-52-00: DF Exception: Sub: R1393T, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-52-44: DF Exception: Sub: R1395M, Sess: 2, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-52-51: DF Exception: Sub: R1396T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-52-57: DF Exception: Sub: R1395M, Sess: 5, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-53-02: DF Exception: Sub: R1395M, Sess: 6, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-53-15: DF Exception: Sub: R1400N, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-53-22: DF Exception: Sub: R1400N, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-53-22: DF Exception: Sub: R1400N, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-53-23: DF Exception: Sub: R1400N, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-53-24: DF Exception: Sub: R1398J, Sess: 1, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-53-27: DF Exception: Sub: R1401J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-53-27: DF Exception: Sub: R1401J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-53-28: DF Exception: Sub: R1401J, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-53-31: DF Exception: Sub: R1403N, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-53-32: DF Exception: Sub: R1403N, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-53-33: DF Exception: Sub: R1403N, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-53-34: DF Exception: Sub: R1403N, Sess: 4, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-53-36: DF Exception: Sub: R1404E, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-53-37: DF Exception: Sub: R1404E, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-53-49: DF Exception: Sub: R1406M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-53-53: DF Exception: Sub: R1406M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-53-57: DF Exception: Sub: R1406M, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-53-58: DF Exception: Sub: R1406M, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-53-59: DF Exception: Sub: R1408N, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-54-02: DF Exception: Sub: R1408N, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-54-12: DF Exception: Sub: R1409D, Sess: 2, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-54-12: DF Exception: Sub: R1409D, Sess: 1, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-54-14: DF Exception: Sub: R1412M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-54-19: DF Exception: Sub: R1412M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-54-19: DF Exception: Sub: R1412M, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-54-37: DF Exception: Sub: R1420T, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-54-43: DF Exception: Sub: R1421M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-54-44: DF Exception: Sub: R1421M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-54-50: DF Exception: Sub: R1422T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-55-04: DF Exception: Sub: R1426N, Sess: 1, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-55-10: DF Exception: Sub: R1427T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-55-11: DF Exception: Sub: R1433E, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-55-15: DF Exception: Sub: R1441T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-55-16: DF Exception: Sub: R1441T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-55-29: DF Exception: Sub: R1436J, Sess: 6, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-55-42: DF Exception: Sub: R1445E, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-56-08: DF Exception: Sub: R1450D, Sess: 1, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-56-18: DF Exception: Sub: R1450D, Sess: 3, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-56-18: DF Exception: Sub: R1450D, Sess: 4, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-56-26: DF Exception: Sub: R1456D, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-56-31: DF Exception: Sub: R1456D, Sess: 1, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-56-32: DF Exception: Sub: R1456D, Sess: 2, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-56-35: DF Exception: Sub: R1457T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-56-36: DF Exception: Sub: R1456D, Sess: 3, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-56-39: DF Exception: Sub: R1459M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-56-42: DF Exception: Sub: R1462M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-57-04: DF Exception: Sub: R1465D, Sess: 1, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-57-14: DF Exception: Sub: R1466J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-57-28: DF Exception: Sub: R1467M, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-57-38: DF Exception: Sub: R1468J, Sess: 3, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-58-07: DF Exception: Sub: R1469D, Sess: 1, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-58-08: DF Exception: Sub: R1472T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-58-15: DF Exception: Sub: R1472T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-58-51: DF Exception: Sub: R1475J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-58-51: DF Exception: Sub: R1475J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-58-54: DF Exception: Sub: R1475J, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_13-59-09: DF Exception: Sub: R1476J, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-59-11: DF Exception: Sub: R1476J, Sess: 2, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_13-59-47: DF Exception: Sub: R1478T, Sess: 0, ValueError, len(channels) (188) must be the same length as the second data dimension (186), file: create_events_mne.py, line no: 515
2024-05-27_13-59-54: DF Exception: Sub: R1478T, Sess: 1, ValueError, len(channels) (188) must be the same length as the second data dimension (186), file: create_events_mne.py, line no: 515
2024-05-27_14-00-09: DF Exception: Sub: R1484T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-00-15: DF Exception: Sub: R1484T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-00-17: DF Exception: Sub: R1485J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-00-17: DF Exception: Sub: R1485J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-00-21: DF Exception: Sub: R1485J, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-00-22: DF Exception: Sub: R1485J, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-00-25: DF Exception: Sub: R1486J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-00-27: DF Exception: Sub: R1486J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-00-29: DF Exception: Sub: R1486J, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-00-30: DF Exception: Sub: R1486J, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-00-39: DF Exception: Sub: R1487T, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-00-40: DF Exception: Sub: R1487T, Sess: 1, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-00-58: DF Exception: Sub: R1488T, Sess: 3, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-00-58: DF Exception: Sub: R1488T, Sess: 2, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-01-33: DF Exception: Sub: R1490T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-01-38: DF Exception: Sub: R1490T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-01-39: DF Exception: Sub: R1490T, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-01-52: DF Exception: Sub: R1491T, Sess: 4, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-01-53: DF Exception: Sub: R1491T, Sess: 2, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-01-55: DF Exception: Sub: R1492J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-01-59: DF Exception: Sub: R1492J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-01-59: DF Exception: Sub: R1492J, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-02-00: DF Exception: Sub: R1492J, Sess: 4, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-02-00: DF Exception: Sub: R1493T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-02-03: DF Exception: Sub: R1493T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-02-04: DF Exception: Sub: R1493T, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-02-04: DF Exception: Sub: R1493T, Sess: 4, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-02-05: DF Exception: Sub: R1495J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-02-09: DF Exception: Sub: R1495J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-02-09: DF Exception: Sub: R1495J, Sess: 10, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-02-10: DF Exception: Sub: R1495J, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-02-11: DF Exception: Sub: R1495J, Sess: 4, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-02-14: DF Exception: Sub: R1495J, Sess: 5, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-02-14: DF Exception: Sub: R1495J, Sess: 6, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-02-15: DF Exception: Sub: R1495J, Sess: 8, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-02-23: DF Exception: Sub: R1497T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-02-23: DF Exception: Sub: R1497T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-02-30: DF Exception: Sub: R1497T, Sess: 4, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-02-30: DF Exception: Sub: R1497T, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-02-30: DF Exception: Sub: R1497T, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-02-51: DF Exception: Sub: R1500T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-02-53: DF Exception: Sub: R1500T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-02-53: DF Exception: Sub: R1500T, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-02-54: DF Exception: Sub: R1500T, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-03-10: DF Exception: Sub: R1505J, Sess: 1, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-04-24: DF Exception: Sub: R1526J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-04-32: DF Exception: Sub: R1525J, Sess: 6, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-04-52: DF Exception: Sub: R1527J, Sess: 1, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-05-02: DF Exception: Sub: R1530J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-05-09: DF Exception: Sub: R1530J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-05-10: DF Exception: Sub: R1530J, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-05-15: DF Exception: Sub: R1530J, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-05-16: DF Exception: Sub: R1530J, Sess: 4, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-05-16: DF Exception: Sub: R1530J, Sess: 6, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-05-19: DF Exception: Sub: R1532T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-05-21: DF Exception: Sub: R1532T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-05-41: DF Exception: Sub: R1537T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-06-10: DF Exception: Sub: R1542J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-06-20: DF Exception: Sub: R1542J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-06-52: DF Exception: Sub: R1616S, Sess: 5, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-06-53: DF Exception: Sub: R1616S, Sess: 4, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-07-11: DF Exception: Sub: R1617S, Sess: 6, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-07-14: DF Exception: Sub: R1626S, Sess: 0, ValueError, len(channels) (189) must be the same length as the second data dimension (156), file: create_events_mne.py, line no: 515
2024-05-27_14-07-20: DF Exception: Sub: R1626S, Sess: 3, ValueError, len(channels) (189) must be the same length as the second data dimension (156), file: create_events_mne.py, line no: 515
2024-05-27_14-07-20: DF Exception: Sub: R1626S, Sess: 2, ValueError, len(channels) (189) must be the same length as the second data dimension (156), file: create_events_mne.py, line no: 515
2024-05-27_14-07-22: DF Exception: Sub: R1626S, Sess: 4, ValueError, len(channels) (189) must be the same length as the second data dimension (156), file: create_events_mne.py, line no: 515
2024-05-27_14-07-22: DF Exception: Sub: R1617S, Sess: 7, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-07-25: DF Exception: Sub: R1626S, Sess: 7, ValueError, len(channels) (189) must be the same length as the second data dimension (156), file: create_events_mne.py, line no: 515
2024-05-27_14-07-25: DF Exception: Sub: R1626S, Sess: 6, ValueError, len(channels) (189) must be the same length as the second data dimension (156), file: create_events_mne.py, line no: 515
2024-05-27_14-07-26: DF Exception: Sub: R1626S, Sess: 8, ValueError, could not broadcast input array from shape (191,100) into shape (191), file: create_events_mne.py, line no: 452
2024-05-27_14-07-41: DF Exception: Sub: R1627T, Sess: 1, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-07-53: DF Exception: Sub: R1637T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-08-27: DF Exception: Sub: R1642J, Sess: 1, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-08-30: DF Exception: Sub: R1642J, Sess: 3, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-09-03: DF Exception: Sub: R1652A, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-09-30: DF Exception: Sub: R1655S, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-09-36: DF Exception: Sub: R1655S, Sess: 2, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-09-42: DF Exception: Sub: R1655S, Sess: 4, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-09-54: DF Exception: Sub: R1658S, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-10-08: DF Exception: Sub: R1659A, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-10-10: DF Exception: Sub: R1658S, Sess: 6, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-10-11: DF Exception: Sub: R1659A, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-10-13: DF Exception: Sub: R1659A, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-10-14: DF Exception: Sub: R1659A, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-10-17: DF Exception: Sub: R1662S, Sess: 10, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-10-18: DF Exception: Sub: R1662S, Sess: 4, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-10-20: DF Exception: Sub: R1662S, Sess: 5, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-10-20: DF Exception: Sub: R1662S, Sess: 6, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-10-24: DF Exception: Sub: R1662S, Sess: 7, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-10-24: DF Exception: Sub: R1662S, Sess: 8, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-10-32: DF Exception: Sub: R1665J, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-10-33: DF Exception: Sub: R1665J, Sess: 1, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-10-34: DF Exception: Sub: R1666S, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-10-40: DF Exception: Sub: R1665J, Sess: 2, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-10-41: DF Exception: Sub: R1666S, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-10-42: DF Exception: Sub: R1666S, Sess: 4, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-10-42: DF Exception: Sub: R1666S, Sess: 5, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-10-47: DF Exception: Sub: R1666S, Sess: 6, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-10-48: DF Exception: Sub: R1666S, Sess: 7, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-11-04: DF Exception: Sub: R1670J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-11-08: DF Exception: Sub: R1668S, Sess: 4, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-11-11: DF Exception: Sub: R1670J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-11-11: DF Exception: Sub: R1670J, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-11-12: DF Exception: Sub: R1670J, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-12-07: DF Exception: Sub: R1674A, Sess: 2, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-12-18: DF Exception: Sub: R1674A, Sess: 3, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-12-24: DF Exception: Sub: R1676J, Sess: 1, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-12-25: DF Exception: Sub: R1676J, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-12-28: DF Exception: Sub: R1678T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-12-31: DF Exception: Sub: R1676J, Sess: 2, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-12-32: DF Exception: Sub: R1678T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-12-34: DF Exception: Sub: R1678T, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-12-40: DF Exception: Sub: R1679J, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-13-01: DF Exception: Sub: R1681J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-13-01: DF Exception: Sub: R1681J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-13-28: DF Exception: Sub: R1696L, Sess: 0, ValueError, len(channels) (196) must be the same length as the second data dimension (179), file: create_events_mne.py, line no: 515
2024-05-27_14-13-31: DF Exception: Sub: R1689J, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-15-35: DF Exception: Sub: R1016M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-15-38: DF Exception: Sub: R1004D, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-15-44: DF Exception: Sub: R1016M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-15-44: DF Exception: Sub: R1013E, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-15-47: DF Exception: Sub: R1021D, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-15-51: DF Exception: Sub: R1026D, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-17-05: DF Exception: Sub: R1035M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-17-11: DF Exception: Sub: R1036M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-17-17: DF Exception: Sub: R1041M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-17-20: DF Exception: Sub: R1042M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-17-33: DF Exception: Sub: R1050M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-17-44: DF Exception: Sub: R1060M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-17-51: DF Exception: Sub: R1061T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-18-01: DF Exception: Sub: R1065J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-18-03: DF Exception: Sub: R1065J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-18-12: DF Exception: Sub: R1065J, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-18-12: DF Exception: Sub: R1045E, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-18-14: DF Exception: Sub: R1065J, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-18-17: DF Exception: Sub: R1066P, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-18-18: DF Exception: Sub: R1066P, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-18-19: DF Exception: Sub: R1066P, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-18-24: DF Exception: Sub: R1069M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-18-34: DF Exception: Sub: R1074M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-18-42: DF Exception: Sub: R1075J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-18-50: DF Exception: Sub: R1086M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-19-11: DF Exception: Sub: R1092J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-19-18: DF Exception: Sub: R1093J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-22-09: DF Exception: Sub: R1107J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-22-17: DF Exception: Sub: R1107J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-23-38: DF Exception: Sub: R1111M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-23-39: DF Exception: Sub: R1111M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-23-56: DF Exception: Sub: R1119P, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-23-57: DF Exception: Sub: R1127P, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-24-01: DF Exception: Sub: R1130M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-24-13: DF Exception: Sub: R1135E, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-24-16: DF Exception: Sub: R1135E, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-24-21: DF Exception: Sub: R1138T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-24-23: DF Exception: Sub: R1138T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-24-29: DF Exception: Sub: R1141T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-24-30: DF Exception: Sub: R1141T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-24-37: DF Exception: Sub: R1141T, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-25-30: DF Exception: Sub: R1147P, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-26-26: DF Exception: Sub: R1167M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-26-33: DF Exception: Sub: R1169P, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-26-40: DF Exception: Sub: R1170J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-26-46: DF Exception: Sub: R1170J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-27-14: DF Exception: Sub: R1178P, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-27-47: DF Exception: Sub: R1181E, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-27-49: DF Exception: Sub: R1181E, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-27-53: DF Exception: Sub: R1184M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-27-54: DF Exception: Sub: R1181E, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-28-02: DF Exception: Sub: R1188C, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-28-02: DF Exception: Sub: R1187P, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-28-05: DF Exception: Sub: R1186P, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-28-11: DF Exception: Sub: R1189M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-28-16: DF Exception: Sub: R1191J, Sess: 1, ValueError, Events must correspond to the session with which the reader was initialized: 1 (events correspond to 0), file: create_events_mne.py, line no: 515
2024-05-27_14-28-21: DF Exception: Sub: R1192C, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-28-25: DF Exception: Sub: R1192C, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-28-28: DF Exception: Sub: R1192C, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-28-34: DF Exception: Sub: R1201P, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-28-34: DF Exception: Sub: R1202M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-28-39: DF Exception: Sub: R1202M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-28-42: DF Exception: Sub: R1204T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-29-47: DF Exception: Sub: R1217T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-30-33: DF Exception: Sub: R1222M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-30-40: DF Exception: Sub: R1226D, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-30-41: DF Exception: Sub: R1226D, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-30-48: DF Exception: Sub: R1226D, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-30-48: DF Exception: Sub: R1226D, Sess: 4, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-30-53: DF Exception: Sub: R1227T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-30-59: DF Exception: Sub: R1229M, Sess: 0, ValueError, Events must correspond to the session with which the reader was initialized: 0 (events correspond to 1), file: create_events_mne.py, line no: 515
2024-05-27_14-31-07: DF Exception: Sub: R1231M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-31-08: DF Exception: Sub: R1230J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-31-14: DF Exception: Sub: R1235E, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-31-15: DF Exception: Sub: R1235E, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-31-48: DF Exception: Sub: R1240T, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-32-03: DF Exception: Sub: R1243T, Sess: 1, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-32-13: DF Exception: Sub: R1245E, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-32-56: DF Exception: Sub: R1251M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-33-28: DF Exception: Sub: R1264P, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-33-28: DF Exception: Sub: R1264P, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-34-33: DF Exception: Sub: R1269E, Sess: 3, ValueError, Events must correspond to the session with which the reader was initialized: 3 (events correspond to 10), file: create_events_mne.py, line no: 515
2024-05-27_14-34-40: DF Exception: Sub: R1271P, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-34-46: DF Exception: Sub: R1271P, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-34-50: DF Exception: Sub: R1273D, Sess: 0, ValueError, Events must correspond to the session with which the reader was initialized: 0 (events correspond to 1), file: create_events_mne.py, line no: 515
2024-05-27_14-34-51: DF Exception: Sub: R1271P, Sess: 4, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-34-55: DF Exception: Sub: R1273D, Sess: 1, ValueError, Events must correspond to the session with which the reader was initialized: 1 (events correspond to 2), file: create_events_mne.py, line no: 515
2024-05-27_14-34-55: DF Exception: Sub: R1273D, Sess: 2, ValueError, Events must correspond to the session with which the reader was initialized: 2 (events correspond to 3), file: create_events_mne.py, line no: 515
2024-05-27_14-35-00: DF Exception: Sub: R1274T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-35-01: DF Exception: Sub: R1274T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-35-07: DF Exception: Sub: R1274T, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-35-09: DF Exception: Sub: R1275D, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-35-16: DF Exception: Sub: R1277J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-35-19: DF Exception: Sub: R1277J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-36-35: DF Exception: Sub: R1290M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-36-39: DF Exception: Sub: R1291M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-36-43: DF Exception: Sub: R1291M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-36-44: DF Exception: Sub: R1302M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-36-47: DF Exception: Sub: R1293P, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-36-50: DF Exception: Sub: R1302M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-37-00: DF Exception: Sub: R1313J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-37-08: DF Exception: Sub: R1317D, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-37-13: DF Exception: Sub: R1303E, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-37-38: DF Exception: Sub: R1321M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-37-44: DF Exception: Sub: R1321M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-37-45: DF Exception: Sub: R1324M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-40-12: DF Exception: Sub: R1334T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-41-10: DF Exception: Sub: R1338T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-42-26: DF Exception: Sub: R1351M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-42-27: DF Exception: Sub: R1351M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-43-39: DF Exception: Sub: R1361C, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-44-00: DF Exception: Sub: R1364C, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-44-03: DF Exception: Sub: R1361C, Sess: 1, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-44-21: DF Exception: Sub: R1364C, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-44-44: DF Exception: Sub: R1368T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-45-10: DF Exception: Sub: R1372C, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-45-33: DF Exception: Sub: R1372C, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-45-36: DF Exception: Sub: R1372C, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-45-55: DF Exception: Sub: R1375C, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-46-14: DF Exception: Sub: R1375C, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-46-23: DF Exception: Sub: R1375C, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-46-32: DF Exception: Sub: R1375C, Sess: 4, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-47-15: DF Exception: Sub: R1378T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-47-20: DF Exception: Sub: R1378T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-49-30: DF Exception: Sub: R1384J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-49-32: DF Exception: Sub: R1384J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-49-58: DF Exception: Sub: R1386T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-50-30: DF Exception: Sub: R1388T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-50-35: DF Exception: Sub: R1388T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-50-43: DF Exception: Sub: R1389J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-50-50: DF Exception: Sub: R1389J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-50-57: DF Exception: Sub: R1389J, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-51-01: DF Exception: Sub: R1389J, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-51-03: DF Exception: Sub: R1390M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-51-04: DF Exception: Sub: R1390M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-51-04: DF Exception: Sub: R1390M, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-51-08: DF Exception: Sub: R1390M, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-51-13: DF Exception: Sub: R1393T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-51-22: DF Exception: Sub: R1393T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-51-25: DF Exception: Sub: R1393T, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-52-29: DF Exception: Sub: R1396T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-52-37: DF Exception: Sub: R1395M, Sess: 6, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-53-04: DF Exception: Sub: R1400N, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-53-06: DF Exception: Sub: R1400N, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-53-07: DF Exception: Sub: R1398J, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_14-53-09: DF Exception: Sub: R1400N, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-53-12: DF Exception: Sub: R1400N, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-53-15: DF Exception: Sub: R1401J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-53-16: DF Exception: Sub: R1401J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-53-16: DF Exception: Sub: R1401J, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-53-18: DF Exception: Sub: R1403N, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-53-21: DF Exception: Sub: R1403N, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-53-23: DF Exception: Sub: R1403N, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-53-23: DF Exception: Sub: R1403N, Sess: 4, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-53-26: DF Exception: Sub: R1404E, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-53-28: DF Exception: Sub: R1404E, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-53-38: DF Exception: Sub: R1406M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-53-46: DF Exception: Sub: R1406M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-53-51: DF Exception: Sub: R1406M, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-53-57: DF Exception: Sub: R1406M, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-54-03: DF Exception: Sub: R1408N, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-54-09: DF Exception: Sub: R1408N, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-54-40: DF Exception: Sub: R1412M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-54-40: DF Exception: Sub: R1412M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-54-47: DF Exception: Sub: R1412M, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-55-12: DF Exception: Sub: R1421M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-55-19: DF Exception: Sub: R1421M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-55-20: DF Exception: Sub: R1422T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-55-37: DF Exception: Sub: R1426N, Sess: 1, ValueError, could not broadcast input array from shape (121,5000) into shape (121), file: create_events_mne.py, line no: 515
2024-05-27_14-55-46: DF Exception: Sub: R1427T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-55-54: DF Exception: Sub: R1433E, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-56-03: DF Exception: Sub: R1441T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-56-10: DF Exception: Sub: R1441T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-56-54: DF Exception: Sub: R1445E, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-59-23: DF Exception: Sub: R1457T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-59-29: DF Exception: Sub: R1459M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_14-59-38: DF Exception: Sub: R1462M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-00-41: DF Exception: Sub: R1466J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-02-05: DF Exception: Sub: R1472T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-02-14: DF Exception: Sub: R1472T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-03-25: DF Exception: Sub: R1475J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-03-33: DF Exception: Sub: R1475J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-03-34: DF Exception: Sub: R1475J, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-04-50: DF Exception: Sub: R1478T, Sess: 0, ValueError, len(channels) (188) must be the same length as the second data dimension (186), file: create_events_mne.py, line no: 515
2024-05-27_15-04-55: DF Exception: Sub: R1478T, Sess: 1, ValueError, len(channels) (188) must be the same length as the second data dimension (186), file: create_events_mne.py, line no: 515
2024-05-27_15-05-07: DF Exception: Sub: R1484T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-05-20: DF Exception: Sub: R1484T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-05-28: DF Exception: Sub: R1485J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-05-36: DF Exception: Sub: R1485J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-05-43: DF Exception: Sub: R1485J, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-05-51: DF Exception: Sub: R1485J, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-05-53: DF Exception: Sub: R1486J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-06-01: DF Exception: Sub: R1486J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-06-04: DF Exception: Sub: R1486J, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-06-11: DF Exception: Sub: R1486J, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-06-22: DF Exception: Sub: R1488T, Sess: 0, IndexError, index 91 is out of bounds for axis 0 with size 91, file: create_events_mne.py, line no: 487
2024-05-27_15-07-41: DF Exception: Sub: R1490T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-07-46: DF Exception: Sub: R1490T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-07-51: DF Exception: Sub: R1490T, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-08-29: DF Exception: Sub: R1492J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-08-36: DF Exception: Sub: R1492J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-08-38: DF Exception: Sub: R1492J, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-08-42: DF Exception: Sub: R1492J, Sess: 4, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-08-43: DF Exception: Sub: R1493T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-08-45: DF Exception: Sub: R1493T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-08-50: DF Exception: Sub: R1493T, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-08-50: DF Exception: Sub: R1493T, Sess: 4, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-08-53: DF Exception: Sub: R1495J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-08-57: DF Exception: Sub: R1495J, Sess: 10, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-08-57: DF Exception: Sub: R1495J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-09-00: DF Exception: Sub: R1495J, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-09-04: DF Exception: Sub: R1495J, Sess: 4, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-09-04: DF Exception: Sub: R1495J, Sess: 5, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-09-06: DF Exception: Sub: R1495J, Sess: 6, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-09-07: DF Exception: Sub: R1495J, Sess: 8, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-09-13: DF Exception: Sub: R1497T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-09-15: DF Exception: Sub: R1497T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-09-23: DF Exception: Sub: R1497T, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-09-23: DF Exception: Sub: R1497T, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-09-30: DF Exception: Sub: R1497T, Sess: 4, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-10-06: DF Exception: Sub: R1500T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-10-08: DF Exception: Sub: R1500T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-10-10: DF Exception: Sub: R1500T, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-10-15: DF Exception: Sub: R1500T, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-12-09: DF Exception: Sub: R1525J, Sess: 4, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_15-12-23: DF Exception: Sub: R1526J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-13-20: DF Exception: Sub: R1530J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-13-22: DF Exception: Sub: R1530J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-13-27: DF Exception: Sub: R1530J, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-13-29: DF Exception: Sub: R1530J, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-13-29: DF Exception: Sub: R1530J, Sess: 4, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-13-30: DF Exception: Sub: R1530J, Sess: 6, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-13-34: DF Exception: Sub: R1532T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-13-37: DF Exception: Sub: R1532T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-14-05: DF Exception: Sub: R1537T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-14-40: DF Exception: Sub: R1542J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-14-51: DF Exception: Sub: R1542J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-16-40: DF Exception: Sub: R1626S, Sess: 0, ValueError, len(channels) (189) must be the same length as the second data dimension (156), file: create_events_mne.py, line no: 515
2024-05-27_15-16-46: DF Exception: Sub: R1626S, Sess: 2, ValueError, len(channels) (189) must be the same length as the second data dimension (156), file: create_events_mne.py, line no: 515
2024-05-27_15-16-48: DF Exception: Sub: R1626S, Sess: 3, ValueError, len(channels) (189) must be the same length as the second data dimension (156), file: create_events_mne.py, line no: 515
2024-05-27_15-16-52: DF Exception: Sub: R1626S, Sess: 4, ValueError, len(channels) (189) must be the same length as the second data dimension (156), file: create_events_mne.py, line no: 515
2024-05-27_15-16-53: DF Exception: Sub: R1626S, Sess: 6, ValueError, len(channels) (189) must be the same length as the second data dimension (156), file: create_events_mne.py, line no: 515
2024-05-27_15-16-53: DF Exception: Sub: R1626S, Sess: 7, ValueError, len(channels) (189) must be the same length as the second data dimension (156), file: create_events_mne.py, line no: 515
2024-05-27_15-16-57: DF Exception: Sub: R1626S, Sess: 8, ValueError, len(channels) (189) must be the same length as the second data dimension (156), file: create_events_mne.py, line no: 515
2024-05-27_15-17-22: DF Exception: Sub: R1637T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-18-39: DF Exception: Sub: R1642J, Sess: 3, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_15-21-15: DF Exception: Sub: R1659A, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-21-22: DF Exception: Sub: R1659A, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-21-22: DF Exception: Sub: R1659A, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-21-30: DF Exception: Sub: R1659A, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-21-31: DF Exception: Sub: R1662S, Sess: 10, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-21-38: DF Exception: Sub: R1662S, Sess: 4, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-21-39: DF Exception: Sub: R1662S, Sess: 5, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-21-42: DF Exception: Sub: R1662S, Sess: 6, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-21-46: DF Exception: Sub: R1662S, Sess: 7, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-21-46: DF Exception: Sub: R1662S, Sess: 8, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-22-00: DF Exception: Sub: R1666S, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-22-07: DF Exception: Sub: R1666S, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-22-10: DF Exception: Sub: R1666S, Sess: 4, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-22-14: DF Exception: Sub: R1666S, Sess: 5, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-22-16: DF Exception: Sub: R1666S, Sess: 6, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-22-19: DF Exception: Sub: R1666S, Sess: 7, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-23-06: DF Exception: Sub: R1670J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-23-06: DF Exception: Sub: R1670J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-23-09: DF Exception: Sub: R1670J, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-23-12: DF Exception: Sub: R1670J, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-25-03: DF Exception: Sub: R1676J, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_15-25-11: DF Exception: Sub: R1678T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-25-12: DF Exception: Sub: R1676J, Sess: 1, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_15-25-14: DF Exception: Sub: R1678T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-25-17: DF Exception: Sub: R1678T, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-25-27: DF Exception: Sub: R1676J, Sess: 2, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-05-27_15-25-50: DF Exception: Sub: R1681J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-25-55: DF Exception: Sub: R1681J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 568
2024-05-27_15-26-21: DF Exception: Sub: R1696L, Sess: 0, ValueError, len(channels) (196) must be the same length as the second data dimension (179), file: create_events_mne.py, line no: 515
2024-05-27_15-26-29: DF Exception: Sub: R1689J, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 649
2024-06-14_20-27-40: DF Exception: Sub: R1016M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_20-27-47: DF Exception: Sub: R1016M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_20-27-48: DF Exception: Sub: R1013E, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_20-27-53: DF Exception: Sub: R1021D, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_20-27-59: DF Exception: Sub: R1026D, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_20-28-04: DF Exception: Sub: R1028M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_20-28-12: DF Exception: Sub: R1028M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_20-30-34: DF Exception: Sub: R1036M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_20-30-42: DF Exception: Sub: R1041M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_20-30-47: DF Exception: Sub: R1042M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_20-33-02: DF Exception: Sub: R1045E, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 647
2024-06-14_20-33-06: DF Exception: Sub: R1050M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_20-33-08: DF Exception: Sub: R1056M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=int64)), file: create_events_mne.py, line no: 566
2024-06-14_20-33-11: DF Exception: Sub: R1060M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_20-58-10: DF Exception: Sub: R1069M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_20-58-15: DF Exception: Sub: R1074M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_20-58-22: DF Exception: Sub: R1075J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_20-58-36: DF Exception: Sub: R1083J, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 647
2024-06-14_21-00-00: DF Exception: Sub: R1093J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-01-23: DF Exception: Sub: R1106M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=int64)), file: create_events_mne.py, line no: 566
2024-06-14_21-01-29: DF Exception: Sub: R1107J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-01-31: DF Exception: Sub: R1107J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-11-35: DF Exception: Sub: R1111M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-11-40: DF Exception: Sub: R1111M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-12-11: DF Exception: Sub: R1114C, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-12-17: DF Exception: Sub: R1119P, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-13-20: DF Exception: Sub: R1130M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-13-41: DF Exception: Sub: R1135E, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-13-56: DF Exception: Sub: R1135E, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-15-11: DF Exception: Sub: R1141T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-15-18: DF Exception: Sub: R1141T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-15-23: DF Exception: Sub: R1141T, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-25-53: DF Exception: Sub: R1169P, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 647
2024-06-14_21-25-56: DF Exception: Sub: R1170J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-26-00: DF Exception: Sub: R1170J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-26-11: DF Exception: Sub: R1178P, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-27-50: DF Exception: Sub: R1181E, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-27-56: DF Exception: Sub: R1181E, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-28-02: DF Exception: Sub: R1181E, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-28-07: DF Exception: Sub: R1184M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=int64)), file: create_events_mne.py, line no: 566
2024-06-14_21-28-58: DF Exception: Sub: R1189M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-29-43: DF Exception: Sub: R1191J, Sess: 1, ValueError, Events must correspond to the session with which the reader was initialized: 1 (events correspond to 0), file: create_events_mne.py, line no: 513
2024-06-14_21-30-09: DF Exception: Sub: R1202M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-30-14: DF Exception: Sub: R1202M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-33-24: DF Exception: Sub: R1221P, Sess: 2, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 647
2024-06-14_21-33-30: DF Exception: Sub: R1222M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-36-33: DF Exception: Sub: R1229M, Sess: 0, ValueError, Events must correspond to the session with which the reader was initialized: 0 (events correspond to 1), file: create_events_mne.py, line no: 513
2024-06-14_21-36-52: DF Exception: Sub: R1231M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-36-59: DF Exception: Sub: R1235E, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-37-04: DF Exception: Sub: R1235E, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-41-28: DF Exception: Sub: R1251M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-42-38: DF Exception: Sub: R1266J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-42-46: DF Exception: Sub: R1266J, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-42-53: DF Exception: Sub: R1266J, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-42-59: DF Exception: Sub: R1266J, Sess: 5, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-46-07: DF Exception: Sub: R1269E, Sess: 3, ValueError, Events must correspond to the session with which the reader was initialized: 3 (events correspond to 10), file: create_events_mne.py, line no: 513
2024-06-14_21-46-54: DF Exception: Sub: R1273D, Sess: 0, ValueError, Events must correspond to the session with which the reader was initialized: 0 (events correspond to 1), file: create_events_mne.py, line no: 513
2024-06-14_21-46-57: DF Exception: Sub: R1273D, Sess: 1, ValueError, Events must correspond to the session with which the reader was initialized: 1 (events correspond to 2), file: create_events_mne.py, line no: 513
2024-06-14_21-47-01: DF Exception: Sub: R1273D, Sess: 2, ValueError, Events must correspond to the session with which the reader was initialized: 2 (events correspond to 3), file: create_events_mne.py, line no: 513
2024-06-14_21-47-06: DF Exception: Sub: R1274T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-47-11: DF Exception: Sub: R1274T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-47-16: DF Exception: Sub: R1274T, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-48-51: DF Exception: Sub: R1277J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-48-58: DF Exception: Sub: R1277J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-55-02: DF Exception: Sub: R1290M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-56-56: DF Exception: Sub: R1302M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_21-57-02: DF Exception: Sub: R1302M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-00-21: DF Exception: Sub: R1317D, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-01-40: DF Exception: Sub: R1321M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-01-48: DF Exception: Sub: R1321M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-01-55: DF Exception: Sub: R1324M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-22-55: DF Exception: Sub: R1351M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-22-55: DF Exception: Sub: R1351M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-28-02: DF Exception: Sub: R1364C, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-28-29: DF Exception: Sub: R1364C, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-31-15: DF Exception: Sub: R1370E, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-34-15: DF Exception: Sub: R1375C, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-34-26: DF Exception: Sub: R1375C, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-34-34: DF Exception: Sub: R1375C, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-34-44: DF Exception: Sub: R1375C, Sess: 4, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-35-47: DF Exception: Sub: R1377M, Sess: 6, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 647
2024-06-14_22-36-06: DF Exception: Sub: R1378T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-36-24: DF Exception: Sub: R1378T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-38-21: DF Exception: Sub: R1380D, Sess: 2, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 647
2024-06-14_22-41-53: DF Exception: Sub: R1384J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-42-00: DF Exception: Sub: R1384J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-44-49: DF Exception: Sub: R1389J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-44-51: DF Exception: Sub: R1389J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-44-56: DF Exception: Sub: R1389J, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-44-58: DF Exception: Sub: R1389J, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-45-02: DF Exception: Sub: R1390M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-45-04: DF Exception: Sub: R1390M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-45-08: DF Exception: Sub: R1390M, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-45-10: DF Exception: Sub: R1390M, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-45-14: DF Exception: Sub: R1391T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-45-16: DF Exception: Sub: R1391T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-48-56: DF Exception: Sub: R1400N, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-49-01: DF Exception: Sub: R1400N, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-49-02: DF Exception: Sub: R1400N, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-49-06: DF Exception: Sub: R1400N, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-49-09: DF Exception: Sub: R1401J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-49-12: DF Exception: Sub: R1401J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-49-15: DF Exception: Sub: R1401J, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-49-17: DF Exception: Sub: R1403N, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-49-21: DF Exception: Sub: R1403N, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-49-22: DF Exception: Sub: R1403N, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-49-28: DF Exception: Sub: R1403N, Sess: 4, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-50-54: DF Exception: Sub: R1406M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-50-59: DF Exception: Sub: R1406M, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-51-05: DF Exception: Sub: R1406M, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-51-11: DF Exception: Sub: R1406M, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-51-17: DF Exception: Sub: R1408N, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-51-22: DF Exception: Sub: R1408N, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-54-38: DF Exception: Sub: R1426N, Sess: 1, ValueError, could not broadcast input array from shape (121,5000) into shape (121), file: create_events_mne.py, line no: 513
2024-06-14_22-55-09: DF Exception: Sub: R1441T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_22-55-15: DF Exception: Sub: R1441T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-01-43: DF Exception: Sub: R1457T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-01-57: DF Exception: Sub: R1462M, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-04-14: DF Exception: Sub: R1466J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-10-33: DF Exception: Sub: R1474T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-10-39: DF Exception: Sub: R1474T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-10-45: DF Exception: Sub: R1474T, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-10-52: DF Exception: Sub: R1475J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-10-58: DF Exception: Sub: R1475J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-11-06: DF Exception: Sub: R1475J, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-15-01: DF Exception: Sub: R1478T, Sess: 0, ValueError, len(channels) (188) must be the same length as the second data dimension (186), file: create_events_mne.py, line no: 513
2024-06-14_23-15-06: DF Exception: Sub: R1478T, Sess: 1, ValueError, len(channels) (188) must be the same length as the second data dimension (186), file: create_events_mne.py, line no: 513
2024-06-14_23-17-26: DF Exception: Sub: R1485J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-17-32: DF Exception: Sub: R1485J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-17-39: DF Exception: Sub: R1485J, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-17-45: DF Exception: Sub: R1485J, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-22-56: DF Exception: Sub: R1488T, Sess: 0, IndexError, index 91 is out of bounds for axis 0 with size 91, file: create_events_mne.py, line no: 485
2024-06-14_23-24-47: DF Exception: Sub: R1490T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-24-52: DF Exception: Sub: R1490T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-24-57: DF Exception: Sub: R1490T, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-25-34: DF Exception: Sub: R1492J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-25-42: DF Exception: Sub: R1492J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-25-50: DF Exception: Sub: R1492J, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-25-57: DF Exception: Sub: R1492J, Sess: 4, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-26-32: DF Exception: Sub: R1495J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-26-39: DF Exception: Sub: R1495J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-26-41: DF Exception: Sub: R1495J, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-26-41: DF Exception: Sub: R1495J, Sess: 10, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-26-45: DF Exception: Sub: R1495J, Sess: 4, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-26-46: DF Exception: Sub: R1495J, Sess: 5, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-26-47: DF Exception: Sub: R1495J, Sess: 6, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-26-48: DF Exception: Sub: R1495J, Sess: 8, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-30-27: DF Exception: Sub: R1500T, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-30-35: DF Exception: Sub: R1500T, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-30-43: DF Exception: Sub: R1500T, Sess: 2, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-30-52: DF Exception: Sub: R1500T, Sess: 3, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-36-14: DF Exception: Sub: R1525J, Sess: 3, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 647
2024-06-14_23-40-22: DF Exception: Sub: R1526J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-14_23-56-45: DF Exception: Sub: R1626S, Sess: 0, ValueError, len(channels) (189) must be the same length as the second data dimension (156), file: create_events_mne.py, line no: 513
2024-06-14_23-56-51: DF Exception: Sub: R1626S, Sess: 2, ValueError, len(channels) (189) must be the same length as the second data dimension (156), file: create_events_mne.py, line no: 513
2024-06-14_23-56-56: DF Exception: Sub: R1626S, Sess: 3, ValueError, len(channels) (189) must be the same length as the second data dimension (156), file: create_events_mne.py, line no: 513
2024-06-14_23-57-02: DF Exception: Sub: R1626S, Sess: 4, ValueError, len(channels) (189) must be the same length as the second data dimension (156), file: create_events_mne.py, line no: 513
2024-06-14_23-57-04: DF Exception: Sub: R1626S, Sess: 6, ValueError, len(channels) (189) must be the same length as the second data dimension (156), file: create_events_mne.py, line no: 513
2024-06-14_23-57-06: DF Exception: Sub: R1626S, Sess: 7, ValueError, len(channels) (189) must be the same length as the second data dimension (156), file: create_events_mne.py, line no: 513
2024-06-14_23-57-08: DF Exception: Sub: R1626S, Sess: 8, ValueError, len(channels) (189) must be the same length as the second data dimension (156), file: create_events_mne.py, line no: 513
2024-06-15_00-00-06: DF Exception: Sub: R1642J, Sess: 1, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 647
2024-06-15_00-00-08: DF Exception: Sub: R1642J, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 647
2024-06-15_00-01-08: DF Exception: Sub: R1642J, Sess: 3, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 647
2024-06-15_00-01-42: DF Exception: Sub: R1642J, Sess: 2, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 647
2024-06-15_00-21-11: DF Exception: Sub: R1676J, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 647
2024-06-15_00-21-53: DF Exception: Sub: R1676J, Sess: 1, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 647
2024-06-15_00-22-25: DF Exception: Sub: R1678T, Sess: 2, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 647
2024-06-15_00-22-32: DF Exception: Sub: R1676J, Sess: 2, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 647
2024-06-15_00-24-19: DF Exception: Sub: R1681J, Sess: 0, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-15_00-24-25: DF Exception: Sub: R1681J, Sess: 1, ValueError, No appropriate channels found for the given picks (array([], dtype=float64)), file: create_events_mne.py, line no: 566
2024-06-15_00-25-08: DF Exception: Sub: R1689J, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: create_events_mne.py, line no: 647
2024-06-15_00-25-12: DF Exception: Sub: R1696L, Sess: 0, ValueError, len(channels) (196) must be the same length as the second data dimension (179), file: create_events_mne.py, line no: 513
